# Generated by Django 6.0 on 2026-01-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0003_alter_cart_id_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data',
            new_name='date',
        ),
    ]
