# Generated by Django 6.0.2 on 2026-02-12 03:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png'])])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='myapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
